spring.application.name=AsteriaAPI
#spring.datasource.url=jdbc:postgresql://localhost:5432/AsteriaDB
#spring.datasource.username=stars
#spring.datasource.password=stars
#spring.jpa.hibernate.ddl-auto=none
#
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
