version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: AsteriaDB
    restart: on-failure
    environment:
      POSTGRES_USER: Asteria
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: AsteriaDB
    ports:
      - "5434:5432"
    volumes:
      - pg_data_asteria:/var/lib/postgresql/data

volumes:
  pg_data_asteria:
